### ISSUE TITLE
AttributeError: module 'httpcore' has no attribute 'ConnectionPool'

### ISSUE THREAD

**Issue by sb52pj** [Aghababaei/PhD-Seeker#18]
Hi there, thanks for sharing this repo. I'm using `pip install phdseeker`, but it turns out that running `phdseeker -k 'julia'` or sth gives
```
(base) C:\Users\Administrator\Downloads\PhD-Seeker-main\PhD-Seeker-main>phdseeker -k 'julia'
Searching for the Keywords ''julia'' up to 10 pages.
=================================================::[ scholarshipdb ]::=================================================
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\ProgramData\Miniconda3\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "D:\ProgramData\Miniconda3\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "D:\ProgramData\Miniconda3\lib\site-packages\phdseeker-0.4.7-py3.9.egg\phdseeker\main.py", line 243, in checkNewVersion
    response = httpx.get(url)
  File "D:\ProgramData\Miniconda3\lib\site-packages\httpx\_api.py", line 189, in get
    return request(
  File "D:\ProgramData\Miniconda3\lib\site-packages\httpx\_api.py", line 92, in request
    with Client(
  File "D:\ProgramData\Miniconda3\lib\site-packages\httpx\_client.py", line 672, in __init__
    self._transport = self._init_transport(
  File "D:\ProgramData\Miniconda3\lib\site-packages\httpx\_client.py", line 720, in _init_transport
    return HTTPTransport(
  File "D:\ProgramData\Miniconda3\lib\site-packages\httpx\_transports\default.py", line 136, in __init__
    self._pool = httpcore.ConnectionPool(
AttributeError: module 'httpcore' has no attribute 'ConnectionPool'
====================================================::[ findaphd ]::===================================================
 >>> No positions found, change your keyword. <<<
Elapsed time is 2.06
```

python version 3.9.7
pip version 21.2.4 from D:\ProgramData\Miniconda3\lib\site-packages\pip (python 3.9)

**Comment by fardinabbasi** [comment]
same issue!

**Comment by javadr** [comment]
fixed in ver 0.5
